spring:
  application:
    name: animalCare360

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 37408786218-d2tu3b54fgsff0pe1l3bpta25c1aqr7i.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: post

          github:
            client-id: Ov23licUkLvxfEbtpOZS
            client-secret: 467f69dcfde49e6ffeddad51746a4e9e3816fdda
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: post

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://localhost:5432/animal_care
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 91926499

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

